# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-camera-config-1
  namespace: vision-ai-edge
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-camera-data-1
  namespace: vision-ai-edge
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checkov.io/skip1: CKV_K8S_40=This container need to be run as root
    checkov.io/skip2: CKV_K8S_23=This container need to be run as root
    checkov.io/skip3: CKV_K8S_20=This container need to be run as root
    checkov.io/skip4: CKV2_K8S_6=Network policy need to be configured first
  name: ai-camera-integration-1
  namespace: vision-ai-edge
spec:
  selector:
    matchLabels:
      app: ai-camera-integration-1
  template:
    metadata:
      labels:
        app: ai-camera-integration-1
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - infinity
        - sleep
        image: europe-west1-docker.pkg.dev/mde-official-ce-demo/vision-ai-edge/ai-camera-integration:@sha256:e9743ac3dbd7805f397996274dc38743a70d33da4c9e6a8d57e76c70fb1b5a6e
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command: ["true"]
          initialDelaySeconds: 15
          periodSeconds: 10
        name: ai-camera-integration-operations
        readinessProbe:
          exec:
            command: ["true"]
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/lib/viai/camera-config
          name: ai-camera-config-volume
        - mountPath: /var/lib/viai/camera-data
          name: ai-camera-data-volume
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: false
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: ai-camera-config-volume
        persistentVolumeClaim:
          claimName: ai-camera-config-1
      - name: ai-camera-data-volume
        persistentVolumeClaim:
          claimName: ai-camera-data-1
