#
# Copyright 2026 Google LLC
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

version: 2

multi-ecosystem-groups:
  all-security-updates:
    applies-to: "security-updates"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    labels:
      - "SECURITY"
      - "p0"
      - "dependencies"
    assignees:
      - "GoogleCloudPlatform/cloud-solutions-the-repo-admin"

updates:
  - package-ecosystem: "npm"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "all-security-updates"
    patterns:
      - "*"

  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "all-security-updates"
    patterns:
      - "*"

  - package-ecosystem: "pip"
    directories:
      - "/docs"
      - "/projects/ai/agents/examples/deep-search"
      - "/projects/ai/gen-media/marketing-agent/release/ads_agent"
      - "/projects/ai/gen-media/experimental/GetReadywithMe"
      - "/projects/dataflow-gcs-to-alloydb"
      - "/projects/migrate-from-aws-to-google-cloud/eks-to-gke-proxy-migration/locust"
      - "/projects/migrate-from-aws-to-google-cloud/vm-compute-db-modernization/scripts"
      - "/projects/oracle-bigquery-mcp-agent/mcp-server"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "all-security-updates"
    patterns:
      - "*"

  - package-ecosystem: "uv"
    directories:
      - "/projects/ai/agents/examples/deep-search"
      - "/projects/ai/agents/examples/starter-chat-agent"
      - "/projects/ai/agents/examples/starter-genmedia-agent"
      - "/projects/ai/agents/examples/starter-rag-agent"
      - "/projects/ai/gen-media/marketing-agent/release/adk_common"
      - "/projects/ai/gen-media/marketing-agent/release/marketing_agent"
      - "/projects/manufacturing/ops-assistant"
      - "/projects/manufacturing/tech-assistant"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "all-security-updates"
    patterns:
      - "*"

  - package-ecosystem: "maven"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "all-security-updates"
    patterns:
      - "*"

  - package-ecosystem: "gradle"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "all-security-updates"
    patterns:
      - "*"

  - package-ecosystem: "terraform"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "all-security-updates"
    patterns:
      - "*"

  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "all-security-updates"
    patterns:
      - "*"

  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    multi-ecosystem-group: "all-security-updates"
    patterns:
      - "*"
