# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

-- ============================================================================
-- Application Schema Setup inside ORCLPDB1 - PRODUCTION HIGH VOLUME BENCHMARK
-- ============================================================================
PROMPT Configuring enterprise application objects inside PDB...
SET DEFINE OFF;
SET SERVEROUTPUT ON;



-- Idempotent Schema Cleanup to guarantee zero primary/foreign key constraint violations on re-runs
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RB_INTEL_LEDGER_19C.EXPENSES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RB_INTEL_LEDGER_19C.EMPLOYEES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RB_INTEL_LEDGER_19C.EXPENSE_CATEGORIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RB_INTEL_LEDGER_19C.DEPARTMENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RB_INTEL_LEDGER_19C.COUNTRIES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RB_INTEL_LEDGER_19C.REGIONS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 1. Regions Table
CREATE TABLE RB_INTEL_LEDGER_19C.REGIONS (
    REGION_ID NUMBER PRIMARY KEY,
    REGION_NAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(255)
);

-- 2. Countries Table
CREATE TABLE RB_INTEL_LEDGER_19C.COUNTRIES (
    COUNTRY_ID NUMBER PRIMARY KEY,
    COUNTRY_NAME VARCHAR2(100),
    REGION_ID NUMBER REFERENCES RB_INTEL_LEDGER_19C.REGIONS(REGION_ID)
);

-- 3. Departments Table
CREATE TABLE RB_INTEL_LEDGER_19C.DEPARTMENTS (
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(100)
);

-- 4. Expense Categories Table
CREATE TABLE RB_INTEL_LEDGER_19C.EXPENSE_CATEGORIES (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100),
    BUDGET_LIMIT NUMBER(12,2)
);

-- 5. Employees Table
CREATE TABLE RB_INTEL_LEDGER_19C.EMPLOYEES (
    EMP_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    DEPT_ID NUMBER REFERENCES RB_INTEL_LEDGER_19C.DEPARTMENTS(DEPT_ID),
    COUNTRY_ID NUMBER REFERENCES RB_INTEL_LEDGER_19C.COUNTRIES(COUNTRY_ID)
);

-- 6. Expenses Table
CREATE TABLE RB_INTEL_LEDGER_19C.EXPENSES (
    EXPENSE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AMOUNT NUMBER(12,2),
    EXPENSE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MERCHANT_NAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(255),
    STATUS VARCHAR2(50),
    EMP_ID NUMBER REFERENCES RB_INTEL_LEDGER_19C.EMPLOYEES(EMP_ID),
    CATEGORY_ID NUMBER REFERENCES RB_INTEL_LEDGER_19C.EXPENSE_CATEGORIES(CATEGORY_ID)
);

-- Create global public synonym for local backend Python interface query compatibility
CREATE OR REPLACE PUBLIC SYNONYM EXPENSES FOR RB_INTEL_LEDGER_19C.EXPENSES;

-- Grant select and update permissions directly to common database interface user to allow AI status holds/rejections
GRANT SELECT, UPDATE ON RB_INTEL_LEDGER_19C.EXPENSES TO c##datastream;

-- ============================================================================
-- DYNAMIC CONTINUOUS HIGH-VOLUME DATA GENERATOR (50,000 RECORDS)
-- ============================================================================
DECLARE
    v_date TIMESTAMP;
    v_amount NUMBER(12,2);
    v_status VARCHAR2(20);
    v_merchant VARCHAR2(100);
    v_desc VARCHAR2(255);
    v_emp_id NUMBER;
    v_cat_id NUMBER;
    v_country_id NUMBER;
    v_dept_id NUMBER;
    TYPE t_str_arr IS TABLE OF VARCHAR2(100);
    v_merchants t_str_arr := t_str_arr('Google Cloud Platform', 'Apple Store', 'Uber Enterprise', 'Hilton Hotels', 'British Airways', 'Cisco Systems', 'Amazon Web Services', 'Salesforce.com', 'Microsoft Azure', 'WeWork Enterprise');
    v_descs t_str_arr := t_str_arr('Enterprise cloud compute cluster expansion', 'Urgent developer hardware provisioning', 'Client site transfer coordination', 'Global developer summit accommodations', 'Quarterly software licensing renewals', 'Network security appliance hardware upgrade', 'Database storage high-water mark allocation', 'Executive client dinner logistics', 'Urgent SRE emergency hardware replacement', 'Annual SaaS contract commitment');
BEGIN
    DBMS_OUTPUT.PUT_LINE('Seeding baseline categorical metadata...');
    INSERT INTO RB_INTEL_LEDGER_19C.REGIONS (REGION_ID, REGION_NAME, DESCRIPTION) VALUES (1, 'AMER', 'Americas Enterprise Operations');
    INSERT INTO RB_INTEL_LEDGER_19C.REGIONS (REGION_ID, REGION_NAME, DESCRIPTION) VALUES (2, 'EMEA', 'Europe, Middle East & Africa');
    INSERT INTO RB_INTEL_LEDGER_19C.REGIONS (REGION_ID, REGION_NAME, DESCRIPTION) VALUES (3, 'APAC', 'Asia-Pacific Infrastructure');

    INSERT INTO RB_INTEL_LEDGER_19C.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES (101, 'United States', 1);
    INSERT INTO RB_INTEL_LEDGER_19C.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES (102, 'United Kingdom', 2);
    INSERT INTO RB_INTEL_LEDGER_19C.COUNTRIES (COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES (103, 'Japan', 3);

    INSERT INTO RB_INTEL_LEDGER_19C.DEPARTMENTS (DEPT_ID, DEPT_NAME) VALUES (10, 'Cloud Platform Infrastructure');
    INSERT INTO RB_INTEL_LEDGER_19C.DEPARTMENTS (DEPT_ID, DEPT_NAME) VALUES (20, 'Enterprise Security Engineering');
    INSERT INTO RB_INTEL_LEDGER_19C.DEPARTMENTS (DEPT_ID, DEPT_NAME) VALUES (30, 'Global Financial Operations');

    INSERT INTO RB_INTEL_LEDGER_19C.EXPENSE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, BUDGET_LIMIT) VALUES (1, 'Cloud Hosting SLA', 5000000.00);
    INSERT INTO RB_INTEL_LEDGER_19C.EXPENSE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, BUDGET_LIMIT) VALUES (2, 'Hardware Provisioning', 250000.00);
    INSERT INTO RB_INTEL_LEDGER_19C.EXPENSE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, BUDGET_LIMIT) VALUES (3, 'Travel & Entertainment', 100000.00);

    DBMS_OUTPUT.PUT_LINE('Generating 2,000 enterprise employee records...');
    FOR i IN 1..2000 LOOP
        v_dept_id := CASE MOD(i, 3) WHEN 0 THEN 10 WHEN 1 THEN 20 ELSE 30 END;
        v_country_id := CASE MOD(i, 3) WHEN 0 THEN 101 WHEN 1 THEN 102 ELSE 103 END;
        INSERT INTO RB_INTEL_LEDGER_19C.EMPLOYEES (EMP_ID, FIRST_NAME, LAST_NAME, DEPT_ID, COUNTRY_ID)
        VALUES (1000 + i, 'EmpFirst_' || i, 'EmpLast_' || i, v_dept_id, v_country_id);
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('Generating 50,000 continuous expense records across 730 days of historical spend...');
    FOR i IN 1..50000 LOOP
        v_emp_id := 1001 + ABS(MOD(DBMS_RANDOM.RANDOM, 2000));
        v_cat_id := 1 + ABS(MOD(DBMS_RANDOM.RANDOM, 3));
        v_merchant := v_merchants(1 + ABS(MOD(DBMS_RANDOM.RANDOM, 10)));
        v_desc := v_descs(1 + ABS(MOD(DBMS_RANDOM.RANDOM, 10)));
        v_amount := ROUND(DBMS_RANDOM.VALUE(100.00, 25000.00), 2);
        v_date := SYSTIMESTAMP - INTERVAL '1' DAY * ROUND(DBMS_RANDOM.VALUE(0, 730)) - INTERVAL '1' MINUTE * ROUND(DBMS_RANDOM.VALUE(0, 1440));

        -- Ensure high-risk items are distinctly seeded in pending queues
        IF MOD(i, 100) = 0 THEN
            v_status := 'PENDING';
            v_amount := ROUND(DBMS_RANDOM.VALUE(15500.00, 45000.00), 2);
            v_desc := 'Urgent MacBook Pro M3 Max hardware replacement for personal use';
        ELSIF MOD(i, 50) = 0 THEN
            v_status := 'HOLD';
        ELSE
            v_status := 'APPROVED';
        END IF;

        INSERT INTO RB_INTEL_LEDGER_19C.EXPENSES (AMOUNT, EXPENSE_DATE, MERCHANT_NAME, DESCRIPTION, STATUS, EMP_ID, CATEGORY_ID)
        VALUES (v_amount, v_date, v_merchant, v_desc, v_status, v_emp_id, v_cat_id);

        IF MOD(i, 5000) = 0 THEN
            COMMIT;
            DBMS_OUTPUT.PUT_LINE('Committed ' || i || ' expense records...');
        END IF;
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Successfully generated all 50,000 records!');
END;
/

PROMPT Application schema and continuous data generation setup complete.
