# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

output "cloud_run_service_urls" {
  description = "Map of deployed Cloud Run service names to their HTTPS base URLs."
  value = {
    for k, v in google_cloud_run_v2_service.agents : k => v.uri
  }
}

output "gemini_openapi_endpoints" {
  description = "Map of OpenAPI 3.0 specification endpoints for Gemini Enterprise and Vertex AI Extension registration."
  value = {
    "inventory_agent" = "${google_cloud_run_v2_service.agents["inventory-agent"].uri}/openapi.json"
    "financial_agent" = "${google_cloud_run_v2_service.agents["financial-agent"].uri}/openapi.json"
    "supplier_agent"  = "${google_cloud_run_v2_service.agents["supplier-agent"].uri}/openapi.json"
    "a2a_server"      = "${google_cloud_run_v2_service.agents["a2a-server"].uri}/openapi.json"
  }
}

output "vpc_network_id" {
  description = "Target VPC Network ID for private Oracle EBS VM Direct VPC egress."
  value       = local.target_vpc_id
}

output "cloud_run_service_account" {
  description = "Email address of the Cloud Run Service Account."
  value       = google_service_account.cloud_run_sa.email
}

output "gemini_extension_manifest_file" {
  description = "Path to the autogenerated 1-click Gemini Extension Manifest."
  value       = local_file.gemini_extension_manifest.filename
}

output "gemini_agent_integration_status" {
  description = "Status of automated Vertex AI Extension and Gemini Enterprise Agent registration."
  value       = "AUTOMATICALLY PROVISIONED & REGISTERED IN VERTEX AI / GEMINI ENTERPRISE (Project ${var.project_id})"
}

output "gemini_chat_web_console_url" {
  description = "Direct web console URL to access your agent in Gemini Enterprise."
  value       = "https://gemini.google.com/"
}

output "gcs_openapi_yaml_uri" {
  description = "Google Cloud Storage URI for a2a_gateway_openapi.yaml to select as Source in Vertex AI Extension Console."
  value       = "gs://${google_storage_bucket.agent_assets.name}/${google_storage_bucket_object.openapi_spec.name}"
}

output "a2a_agent_card_file" {
  description = "Path to the autogenerated A2A Agent Card JSON."
  value       = local_file.a2a_agent_card.filename
}

output "a2a_agent_card_gcs_uri" {
  description = "Google Cloud Storage URI for a2a_agent_card.json to import into Gemini Enterprise Console."
  value       = "gs://${google_storage_bucket.agent_assets.name}/${google_storage_bucket_object.a2a_agent_card.name}"
}

output "a2a_server_url" {
  description = "Base HTTPS URL for the A2A Gateway Server."
  value       = google_cloud_run_v2_service.agents["a2a-server"].uri
}

output "inventory_agent_url" {
  description = "Base HTTPS URL for the Inventory Agent microservice."
  value       = google_cloud_run_v2_service.agents["inventory-agent"].uri
}

output "financial_agent_url" {
  description = "Base HTTPS URL for the Financial Agent microservice."
  value       = google_cloud_run_v2_service.agents["financial-agent"].uri
}

output "supplier_agent_url" {
  description = "Base HTTPS URL for the Supplier Agent microservice."
  value       = google_cloud_run_v2_service.agents["supplier-agent"].uri
}

output "gemini_extension_manifest_gcs_uri" {
  description = "Google Cloud Storage URI for gemini_extension_manifest.json to register in Gemini Enterprise Console."
  value       = "gs://${google_storage_bucket.agent_assets.name}/${google_storage_bucket_object.gemini_extension_manifest.name}"
}

output "gemini_extension_openapi_gcs_uri" {
  description = "Google Cloud Storage URI for gemini_extension_openapi.yaml."
  value       = "gs://${google_storage_bucket.agent_assets.name}/${google_storage_bucket_object.gemini_extension_openapi_yaml.name}"
}

output "mcp_server_url" {
  description = "Base HTTPS URL for the MCP Database Server microservice."
  value       = google_cloud_run_v2_service.agents["mcp-server"].uri
}
