# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# secrets-store.csi.x-k8s.io requires a multi-line string literal hence the full replacement.
# Tried using vars which is deprecated, and replacements, but couldn't find a way for replacements
# to handle the end of line scenario and it replacing parts of the following line.

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider
spec:
  parameters:
    secrets: |
      - resourceName: "projects/servidio-test-a/secrets/tools/versions/latest"
        path: "tools.yaml"
