# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-neg-controller-manager
  namespace: hybrid-neg-system # kpt-set: ${hybrid-neg-controller-namespace}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hybrid-neg-controller-manager
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: hybrid-neg-controller-manager
    spec:
      containers:
      - name: manager
        image: hybrid-neg-controller-manager
        args:
        - --health-probe-bind-address=:8081 # kpt-set: --health-probe-bind-address=:${probes-port}
        - --metrics-bind-address=:8080 # kpt-set: --metrics-bind-address=:${metrics-port}
        env: []
        ports:
        - containerPort: 8080 # kpt-set: ${metrics-port}
          name: metrics
          protocol: TCP
        - containerPort: 8081 # kpt-set: ${probes-port}
          name: probes
          protocol: TCP
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: hybrid-neg-controller-manager
      terminationGracePeriodSeconds: 300 # kpt-set: ${termination-grace-period-seconds}
