# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Setup service account to be used for the demo
resource "google_service_account" "connector" {
  provider     = google
  account_id   = "connector-service-account"
  display_name = "Terraform Custom Service Account for the Hive-BigQuery-Connector"
}

# TODO: these roles are way too much for any production environment, and is only setup this way for demo purposes.
# Please change before productionizing this.
# Add roles to the service account
resource "google_project_iam_member" "svc-access" {
  for_each = toset([
    "roles/dataproc.admin",
    "roles/storage.admin",
    "roles/bigquery.admin",
    "roles/dataproc.worker",
  ])
  project = data.google_project.project.project_id
  role    = each.key
  member  = "serviceAccount:${google_service_account.connector.email}"
}

# These are permissions for the service account generated by the BigQuery/BigLake connection.
# Again - these are way over privliged permissions - please review and refine before productionizing this.
resource "google_project_iam_member" "bq-connection-sa" {
  for_each = toset([
    "roles/storage.admin",
    "roles/bigquery.admin"
  ])
  project = data.google_project.project.project_id
  role    = each.key
  member  = "serviceAccount:${google_bigquery_connection.dwh.cloud_resource[0].service_account_id}"
}
