//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTask) DeepCopyInto(out *PtTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTask.
func (in *PtTask) DeepCopy() *PtTask {
	if in == nil {
		return nil
	}
	out := new(PtTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskExecution) DeepCopyInto(out *PtTaskExecution) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskExecution.
func (in *PtTaskExecution) DeepCopy() *PtTaskExecution {
	if in == nil {
		return nil
	}
	out := new(PtTaskExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskImages) DeepCopyInto(out *PtTaskImages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskImages.
func (in *PtTaskImages) DeepCopy() *PtTaskImages {
	if in == nil {
		return nil
	}
	out := new(PtTaskImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskList) DeepCopyInto(out *PtTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PtTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskList.
func (in *PtTaskList) DeepCopy() *PtTaskList {
	if in == nil {
		return nil
	}
	out := new(PtTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PtTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskScenario) DeepCopyInto(out *PtTaskScenario) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskScenario.
func (in *PtTaskScenario) DeepCopy() *PtTaskScenario {
	if in == nil {
		return nil
	}
	out := new(PtTaskScenario)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskSpec) DeepCopyInto(out *PtTaskSpec) {
	*out = *in
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = make([]PtTaskExecution, len(*in))
		copy(*out, *in)
	}
	if in.Scenarios != nil {
		in, out := &in.Scenarios, &out.Scenarios
		*out = make(map[string]PtTaskScenario, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make(map[string]PtTaskImages, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Traffics != nil {
		in, out := &in.Traffics, &out.Traffics
		*out = make(map[string][]PtTaskTraffic, len(*in))
		for key, val := range *in {
			var outVal []PtTaskTraffic
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]PtTaskTraffic, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	out.TestingOutput = in.TestingOutput
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskSpec.
func (in *PtTaskSpec) DeepCopy() *PtTaskSpec {
	if in == nil {
		return nil
	}
	out := new(PtTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskStatus) DeepCopyInto(out *PtTaskStatus) {
	*out = *in
	if in.Phases != nil {
		in, out := &in.Phases, &out.Phases
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Archives != nil {
		in, out := &in.Archives, &out.Archives
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskStatus.
func (in *PtTaskStatus) DeepCopy() *PtTaskStatus {
	if in == nil {
		return nil
	}
	out := new(PtTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskTestingOutput) DeepCopyInto(out *PtTaskTestingOutput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskTestingOutput.
func (in *PtTaskTestingOutput) DeepCopy() *PtTaskTestingOutput {
	if in == nil {
		return nil
	}
	out := new(PtTaskTestingOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtTaskTraffic) DeepCopyInto(out *PtTaskTraffic) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtTaskTraffic.
func (in *PtTaskTraffic) DeepCopy() *PtTaskTraffic {
	if in == nil {
		return nil
	}
	out := new(PtTaskTraffic)
	in.DeepCopyInto(out)
	return out
}
