# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: Job
metadata:
  generateName: vllm-job-
  namespace: default
  labels:
    app: vllm-job
spec:
  activeDeadlineSeconds: 7200
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  template:
    metadata:
      labels:
        app: vllm-job
    spec:
      containers:
      - args:
        - --model=$(MODEL_ID)
        command:
        - python3
        - /run-vllm.py
        env:
        - name: RUN_NAME
          value: ORIGIN
        - name: MODEL_ID
          value: google/gemma-2b-it-chatbot
        image: us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/pytorch-vllm-serve:20240220_0936_RC01
        imagePullPolicy: IfNotPresent
        name: inference-server
        resources:
          limits:
            cpu: "2"
            ephemeral-storage: 20Gi
            memory: 20Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "2"
            ephemeral-storage: 20Gi
            memory: 20Gi
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /run-vllm.py
          name: code
          subPath: run-vllm.py
      dnsPolicy: ClusterFirst
      nodeSelector:
        cloud.google.com/gke-accelerator: some-nvidia-gpu
      restartPolicy: Never
      schedulerName: default-scheduler
      tolerations:
      - effect: NoSchedule
        key: ondemand
        operator: Exists
      - effect: NoSchedule
        key: nvidia/gpu
        operator: Exists
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
      - name: code
        configMap:
          name: model-loading-code
