# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: "Get GKE Credentials"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "container",
        "clusters",
        "get-credentials",
        "${_CLUSTER_NAME}",
        "--region",
        "${_REGION}",
        "--project",
        "${PROJECT_ID}",
      ]

  - id: "Create Namespace"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - "kubectl create namespace ${_NAMESPACE} || true" # Suppress "already exists" error

  - id: "Create Service Account"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - "kubectl create serviceaccount ${_KSA_SERVICE_ACCOUNT} --namespace=${_NAMESPACE} || true" # Suppress "already exists" error

  - id: "Annotate Service Account"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "kubectl"
    args:
      [
        "annotate",
        "serviceaccount",
        "${_KSA_SERVICE_ACCOUNT}",
        "--namespace=${_NAMESPACE}",
        "iam.gke.io/gcp-service-account=${_GCP_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com",
        "--overwrite",
      ]

  - id: "Add IAM Policy Binding"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud iam service-accounts add-iam-policy-binding \
          ${_GCP_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com \
          --role roles/iam.workloadIdentityUser \
          --member serviceAccount:${PROJECT_ID}.svc.id.goog[${_NAMESPACE}/${_KSA_SERVICE_ACCOUNT}] || \
        { STATUS=$?; [ $$STATUS -eq 0 ] || [ $$STATUS -eq 1 ] || exit $$STATUS; }
      # Note: Status code 1 is the typical exit code for the "already exists" error.

options:
  pool:
    name: "projects/${PROJECT_ID}/locations/${_REGION}/workerPools/build-pool"
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _CLUSTER_NAME: "adk-demo-cluster"
  _NAMESPACE: "adk-agent-demo"
  _GCP_SERVICE_ACCOUNT: "adk-agent"
  _KSA_SERVICE_ACCOUNT: "adk-agent-ksa"
