steps:
  - name: "docker:27.2.0-dind"
    args: ["buildx", "create", "--use"]
  - name: "docker:27.2.0-dind"
    args:
      [
        "buildx",
        "build",
        "--platform=linux/arm64,linux/amd64",
        "-t",
        "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/custom-k6:latest",
        "--push",
        ".",
      ]
options:
  machineType: "E2_HIGHCPU_8"
