server {
    listen 8080;
    server_name localhost;

    location / {
        proxy_pass http://proxy-demo.test;
        proxy_set_header Host proxy-demo.test;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
