# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-demo
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-demo
  template:
    metadata:
      labels:
        app: proxy-demo
    spec:
      containers:
        - name: proxy-demo
          image: nginx:1.29-alpine
          command: ["/bin/sh", "/mnt/config/start.sh"]
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: proxy-demo-env
          volumeMounts:
            - name: app-config
              mountPath: /mnt/config/start.sh
              subPath: start.sh
            - name: app-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: app-config
              mountPath: /usr/share/nginx/html/index.template.html
              subPath: index.html
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: app-config
          configMap:
            name: proxy-demo-app-config
            defaultMode: 493
