# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: "python:3.11-slim"
    dir: "adk-agent/scripts"
    id: "delete-old-agents"
    entrypoint: "sh"
    env:
      - "PROJECT_ID=${PROJECT_ID}"
      - "REGION=${_REGION}"
    args:
      - "-c"
      - |
        # Install the requirements
        echo "Installing requirements..."
        pip install -r requirements.txt

        # Execute the deployment command
        echo "Starting clean up script..."
        ./clean_up_old_deploys.py --display_name=$_DISPLAY_NAME

options:
  pool:
    name: "projects/${PROJECT_ID}/locations/${_REGION}/workerPools/build-pool"
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _DISPLAY_NAME: "finance-bundle"
