[server]
maxMessageSize = 500
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FF0000"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#FFFFFF"
