# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: /root/.ssh/publickey
kind: ConfigMap
metadata:
  name: environment-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-schema-config
data:
  initialize-database.sh: |
    #!/bin/bash
    set -e

    COUNTER=0
    SLEEP_TIME=10
    DB_READY=1
    INIT_SQL_SCRIPT="/scripts/0-ledger-schema.sql"
    TEST_SQL_SCRIPT="/scripts/1-load-testdata.sh"

    # Capture arguments passed from the Job command
    HOST=${1:-'127.0.0.1'}
    PORT=${2:-'5432'}
    DB_NAME=${3:-'cymbalbank'}

    echo "Host: ${HOST}, Port: ${PORT}, Database: ${DB_NAME}"

    export PGPASSWORD="$POSTGRES_PASSWORD"

    if [ "${DB_READY}" -eq 1 ]; then
      echo "Running initialization script"

      # Wait loop (Safety check)
      until pg_isready --host="${HOST}" --port="${PORT}" --dbname="${DB_NAME}"; do
        echo "Waiting for DB..."
        sleep 5
      done

      # Run Schema
      psql --host="${HOST}" --port="${PORT}" --dbname="${DB_NAME}" --username "$POSTGRES_USER" -f "${INIT_SQL_SCRIPT}"

      if [ $? -gt 0 ]; then
        echo "Problems running the initialization script"
        exit 1
      else
        echo "Run Test Data"
        # Source the test data script so it inherits HOST/PORT variables
        . ${TEST_SQL_SCRIPT}
      fi
    fi

  0-ledger-schema.sql: |
    /* Ledger Schema */
    CREATE TABLE IF NOT EXISTS TRANSACTIONS (
        TRANSACTION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        FROM_ACCT CHAR(10) NOT NULL,
        TO_ACCT CHAR(10) NOT NULL,
        FROM_ROUTE CHAR(9) NOT NULL,
        TO_ROUTE CHAR(9) NOT NULL,
        AMOUNT INT NOT NULL,
        TIMESTAMP TIMESTAMP NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_trans_from ON TRANSACTIONS (FROM_ACCT, FROM_ROUTE, TIMESTAMP);
    CREATE INDEX IF NOT EXISTS idx_trans_to ON TRANSACTIONS (TO_ACCT, TO_ROUTE, TIMESTAMP);

    -- Rules (Idempotent)
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_rules WHERE rulename = 'prevent_update') THEN
        CREATE RULE PREVENT_UPDATE AS ON UPDATE TO TRANSACTIONS DO INSTEAD NOTHING;
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_rules WHERE rulename = 'prevent_delete') THEN
        CREATE RULE PREVENT_DELETE AS ON DELETE TO TRANSACTIONS DO INSTEAD NOTHING;
      END IF;
    END
    $$;

  1-load-testdata.sh: |
    #!/bin/bash
    set -u

    if [ "${USE_DEMO_DATA:-}" != "True" ]; then
        echo "USE_DEMO_DATA not True; no demo transactions added"
        exit 0
    fi

    add_transaction() {
        DATE=$(date -u +"%Y-%m-%d %H:%M:%S%z" --date="@$(($6))")
        echo "adding demo transaction: $1 -> $2"

        # FIX: We use Bash variables directly inside the double-quoted string.
        # Single quotes '$1' wrap the text values for SQL syntax.
        # $5 (Amount) is an integer, so no quotes needed.
        psql -h "${HOST}" -p "${PORT}" -X -v ON_ERROR_STOP=1 \
          --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
          -c "INSERT INTO TRANSACTIONS (FROM_ACCT, TO_ACCT, FROM_ROUTE, TO_ROUTE, AMOUNT, TIMESTAMP) VALUES ('$1', '$2', '$3', '$4', $5, '$DATE');"
    }

    create_transactions() {
        PAY_PERIODS=3
        DAYS_BETWEEN_PAY=14
        SECONDS_IN_PAY_PERIOD=$(( 86400 * $DAYS_BETWEEN_PAY ))
        DEPOSIT_AMOUNT=250000
        START_TIMESTAMP=$(( $(date +%s) - $(( $(($PAY_PERIODS+1)) * $SECONDS_IN_PAY_PERIOD )) ))

        USER_ACCOUNTS=("1011226111" "1033623433" "1055757655" "1077441377")
        EXTERNAL_ACCOUNT="9099791699"
        EXTERNAL_ROUTING="808889588"

        for i in $(seq 1 $PAY_PERIODS); do
            for account in ${USER_ACCOUNTS[@]}; do
                add_transaction "$EXTERNAL_ACCOUNT" "$account" "$EXTERNAL_ROUTING" "$LOCAL_ROUTING_NUM" $DEPOSIT_AMOUNT $START_TIMESTAMP
            done

            TRANSACTIONS_PER_PERIOD=$(shuf -i 15-20 -n1)
            for p in $(seq 1 $TRANSACTIONS_PER_PERIOD); do
                AMOUNT=$(shuf -i 1000-10000 -n1)
                SENDER_ACCOUNT=${USER_ACCOUNTS[$RANDOM % ${#USER_ACCOUNTS[@]}]}
                RECIPIENT_ACCOUNT=${USER_ACCOUNTS[$RANDOM % ${#USER_ACCOUNTS[@]}]}

                if [[ "$SENDER_ACCOUNT" == "$RECIPIENT_ACCOUNT" ]]; then
                    RECIPIENT_ACCOUNT=$(shuf -i 1000000000-9999999999 -n1)
                fi

                TIMESTAMP=$(( $START_TIMESTAMP + $(( $SECONDS_IN_PAY_PERIOD * $p / $(($TRANSACTIONS_PER_PERIOD + 1 )) )) ))
                add_transaction "$SENDER_ACCOUNT" "$RECIPIENT_ACCOUNT" "$LOCAL_ROUTING_NUM" "$LOCAL_ROUTING_NUM" $AMOUNT $TIMESTAMP
            done
            START_TIMESTAMP=$(( $START_TIMESTAMP + $(( $i * $SECONDS_IN_PAY_PERIOD )) ))
        done
    }

    main() {
      create_transactions
    }

    main

---
apiVersion: batch/v1
kind: Job
metadata:
  name: populate-ledger-db
spec:
  template:
    spec:
      serviceAccountName: cymbalbank-sa
      containers:
        - name: populate-ledger-db
          image: postgres:16.6
          command:
            - "bash"
            - "-c"
            # Make sure RDS_ENDPOINT_PLACEHOLDER is replaced in your pipeline or kustomize
            - ". /scripts/initialize-database.sh RDS_ENDPOINT_PLACEHOLDER 5432 ledger-db"
          volumeMounts:
            - name: scripts
              mountPath: "/scripts"
              readOnly: true
          env:
            - name: LOCAL_ROUTING_NUM
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: LOCAL_ROUTING_NUM
                  optional: true
            - name: USE_DEMO_DATA
              value: "True"
            - name: POSTGRES_DB
              value: "ledger-db"
            - name: PGHOST
              value: "RDS_ENDPOINT_PLACEHOLDER"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "RDS_PASSWORD_PLACEHOLDER"
      volumes:
        - name: scripts
          configMap:
            name: ledger-schema-config
      restartPolicy: Never
  backoffLimit: 4
