# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: perftest.com.google.cloud.solutions.satools/v1
kind: PtTask
metadata:
  labels:
    app.kubernetes.io/name: pttask
    app.kubernetes.io/instance: pttask-sample
    app.kubernetes.io/part-of: pt-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pt-operator
  name: pttask-sample
spec:
  type: Local
  execution:
    - executor: locust
      concurrency: 100
      ramp-up: 10s
      hold-for: 5m
      master: True
      workers: 1
      scenario: test-example
  scenarios:
    test-example:
      default-address: http://blazedemo.com
      script: locustfile.py
  images:
    test-example:
      masterImage: asia-docker.pkg.dev/play-api-service/test-images/taurus-base
      workerImage: asia-docker.pkg.dev/play-api-service/test-images/locust-worker
  testingOutput:
    logDir: ./config/samples
    ldjson: ./config/samples/locust-workers.ldjson
    bucket: perf-test-achive-cc
