FROM locustio/locust:2.14.1

# Copy any locust file and nested folder into /bzt-configs
# How to structure your test code: https://docs.locust.io/en/stable/writing-a-locustfile.html#how-to-structure-your-test-code
COPY scripts /bzt-configs



# Setup workdir
WORKDIR /bzt-configs
# Marked as Locust worker, following with master host and any other parameters
# Python module to import, e.g. '../other_test.py'. Either a .py file, multiple comma-separated .py files or a package directory. Defaults to 'locustfile'.
CMD ["locust", "--worker", "--master-host \"$@\""]
