FROM blazemeter/taurus@sha256:5d4a8724a976ffc7b421ae7c4c476a451e7ed56ba0944d9c3f3432bdb7f55557


# Install Locust
RUN pip3 install 'locust==2.14.2' --ignore-installed

# Copy any locust file and nested folder into /bzt-configs
COPY scripts /bzt-configs

# Setup workdir
WORKDIR /bzt-configs
CMD ["/usr/local/bin/bzt", "/taurus-configs/taurus.yaml", "-o", "modules.console.disable=true", "-o", "settings.artifacts-dir=/taurus-logs/%Y-%m-%d_%H-%M-%S.%f"]
